---
# - hosts: all
#   # Basic host setup
#   tasks:
#   - name: Install epel-release
#     yum:
#       name:
#       - epel-release
#       state: latest
#     become: yes
#   - name: Install packages
#     yum:
#       name:
#       - lsof
#       - nmap
#       - screen 
#       - net-tools 
#       - lsof
#       - htop
#       - unzip
#       state: latest
#     become: yes

#   - name: Create bin folder
#     file:
#       path: /home/vagrant/bin
#       state: directory
#       mode: '0755'

#   - name: Check Nomad bin
#     stat:
#       path: "/home/vagrant/bin/nomad"
#     register: nomad_bin

#   - name: Install Nomad
#     unarchive:
#       src: https://releases.hashicorp.com/nomad/1.0.2/nomad_1.0.2_linux_amd64.zip
#       dest: /home/vagrant/bin
#       remote_src: yes
#     when: not nomad_bin.stat.exists

#   - name: Check Consul bin
#     stat:
#       path: "/home/vagrant/bin/consul"
#     register: consul_bin

#   - name: Install Consul
#     unarchive:
#       src: https://releases.hashicorp.com/consul/1.9.2/consul_1.9.2_linux_amd64.zip
#       dest: /home/vagrant/bin
#       remote_src: yes
#     when: not consul_bin.stat.exists

- hosts: servers
  # Server hosts setup
  tasks:
  - name: Create consul_server dirs
    file:
      path: /home/vagrant/consul_server/consul.d
      state: directory
      mode: '0755'

  - name: Deploy consul server config
    copy:
      src: ./resources/consul_server/consul.d/config.json
      dest: /home/vagrant/consul_server/consul.d/config.json
      owner: vagrant
      group: vagrant
      mode: '0644'

  - name: Run Consul server
    command: screen -dmS consul /home/vagrant/bin/consul agent -config-dir ./consul.d
    args:
      chdir: /home/vagrant/consul_server/
