---
# Basic host setup to be applied to fresh VMs
- hosts: all
  tasks:
  - name: Copy ssh config file (allow github ssh over VPN)
    copy:
      src: "~/.ssh/config"
      dest: "/home/vagrant/.ssh/config"
      mode: '0600'
  - name: Install epel-release
    yum:
      name:
      - epel-release
      state: latest
    become: yes
  - name: Install packages
    yum:
      name:
      - lsof
      - nmap
      - telnet
      - tcpdump
      - screen 
      - net-tools 
      - lsof
      - htop
      - unzip
      - bind-utils
      - git
      state: latest
    become: yes

  - name: Create bin folder
    file:
      path: /home/vagrant/bin
      state: directory
      mode: '0755'

  - name: Check Nomad bin
    stat:
      path: "/home/vagrant/bin/nomad"
    register: nomad_bin

  - name: Install Nomad
    unarchive:
      src: https://releases.hashicorp.com/nomad/1.0.3/nomad_1.0.3_linux_amd64.zip
      dest: /home/vagrant/bin
      remote_src: yes
    when: not nomad_bin.stat.exists

  - name: Check Consul bin
    stat:
      path: "/home/vagrant/bin/consul"
    register: consul_bin

  - name: Install Consul
    unarchive:
      src: https://releases.hashicorp.com/consul/1.9.2/consul_1.9.2_linux_amd64.zip
      dest: /home/vagrant/bin
      remote_src: yes
    when: not consul_bin.stat.exists

  - name: Check levant bin
    stat:
      path: "/home/vagrant/bin/levant"
    register: levant_bin

  - name: Install levant
    unarchive:
      src: https://releases.hashicorp.com/levant/0.3.0-beta1/levant_0.3.0-beta1_linux_amd64.zip
      dest: /home/vagrant/bin
      remote_src: yes
    when: not levant_bin.stat.exists

  - name: Check node_exporter bin
    stat:
      path: "/home/vagrant/bin/node_exporter"
    register: node_exporter

  - name: Install node_exporter
    unarchive:
      src: https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
      dest: /home/vagrant/bin
      remote_src: yes
    when: not node_exporter.stat.exists

  - name: Create symlink for node_exporter bin
    file:
      src: "/home/vagrant/bin/node_exporter-1.0.1.linux-amd64/node_exporter"
      dest: "/home/vagrant/bin/node_exporter"
      state: link

  - name: Check fabio bin
    stat:
      path: "/home/vagrant/bin/fabio"
    register: fabio

  - name: Install fabio
    get_url:
      url: https://github.com/fabiolb/fabio/releases/download/v1.5.15/fabio-1.5.15-go1.15.5-linux_amd64
      dest: /home/vagrant/bin/fabio
      mode: '0755'
    when: not fabio.stat.exists

- hosts: itrs_gateways
  tasks:
    - name: Create packages folder
      file:
        path: /home/vagrant/packages
        state: directory
    # Gateway
    - name: Unarchive gateway binaries
      unarchive:
        src: ./packages/geneos-gateway-5.5.1-linux-x64.tar.gz
        dest: /home/vagrant/packages
    - name: Create symlink for gateway bin
      file:
        src: "/home/vagrant/packages/gateway/gateway2.linux_64"
        dest: "/home/vagrant/bin/gateway"
        state: link
    # Netprobe
    - name: Unarchive netprobe binaries
      unarchive:
        src: ./packages/geneos-netprobe-5.5.2-linux-x64.tar.gz
        dest: /home/vagrant/packages
    - name: Create symlink for netprobe bin
      file:
        src: "/home/vagrant/packages/netprobe/netprobe.linux_64"
        dest: "/home/vagrant/bin/netprobe"
        state: link
    # licd
    - name: Unarchive licd binaries
      unarchive:
        src: ./packages/geneos-licd-5.5.0-linux-x64.tar.gz
        dest: /home/vagrant/packages
    - name: Create symlink for licd bin
      file:
        src: "/home/vagrant/packages/licd/licd.linux_64"
        dest: "/home/vagrant/bin/licd"
        state: link

    # TODO: this stuff should go to Vault
    - name: Create not_so_secrets folder
      file:
        path: /home/vagrant/not_so_secrets
        state: directory
    - name: Create not_so_secrets folder
      copy:
        src: "./packages/geneos.lic"
        dest: "/home/vagrant/not_so_secrets/geneos.lic"
