---
- name: Wipe cloned gateway config repo
  file:
    path: "/home/vagrant/gateway_config"
    state: absent
  become: yes

- name: Clone Gateway config repo
  git:
    repo: git@github.com:f4t/gateway-config.git
    dest: /home/vagrant/gateway_config
