---
- hosts: all
  # Basic host setup
  tasks:
  - name: Install epel-release
    yum:
      name:
      - epel-release
      state: latest
    become: yes
  - name: Install packages
    yum:
      name:
      - lsof
      - nmap
      - screen 
      - net-tools 
      - lsof
      - htop
      - unzip
      state: latest
    become: yes

  - name: Create bin folder
    file:
      path: /home/vagrant/bin
      state: directory
      mode: '0755'

  - name: Check Nomad bin
    stat:
      path: "/home/vagrant/bin/nomad"
    register: nomad_bin

  - name: Install Nomad
    unarchive:
      src: https://releases.hashicorp.com/nomad/1.0.2/nomad_1.0.2_linux_amd64.zip
      dest: /home/vagrant/bin
      remote_src: yes
    when: not nomad_bin.stat.exists

  - name: Check Consul bin
    stat:
      path: "/home/vagrant/bin/consul"
    register: consul_bin

  - name: Install Consul
    unarchive:
      src: https://releases.hashicorp.com/consul/1.9.2/consul_1.9.2_linux_amd64.zip
      dest: /home/vagrant/bin
      remote_src: yes
    when: not consul_bin.stat.exists

  - name: Check node_exporter bin
    stat:
      path: "/home/vagrant/bin/node_exporter"
    register: node_exporter

  - name: Install node_exporter
    unarchive:
      src: https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
      dest: /home/vagrant/bin
      remote_src: yes
    when: not node_exporter.stat.exists

  - name: Create symlink for node_exporter bin
    file:
      src: "/home/vagrant/bin/node_exporter-1.0.1.linux-amd64/node_exporter"
      dest: "/home/vagrant/bin/node_exporter"
      state: link

  - name: Check fabio bin
    stat:
      path: "/home/vagrant/bin/fabio"
    register: fabio

  - name: Install fabio
    get_url:
      url: https://github.com/fabiolb/fabio/releases/download/v1.5.15/fabio-1.5.15-go1.15.5-linux_amd64
      dest: /home/vagrant/bin/fabio
      mode: '0755'
    when: not fabio.stat.exists

