---
- hosts: nomad_clients
  # Server hosts setup
  tasks:
  - name: Create nomad_client dir
    file:
      path: /home/vagrant/nomad_client
      state: directory
      mode: '0755'

  - name: Deploy nomad server config
    template:
      src: ./resources/nomad_client/nomad_client.hcl
      dest: /home/vagrant/nomad_client/nomad_client.hcl
      owner: vagrant
      group: vagrant
      mode: 0644

  - name: Kill nomad
    command: pkill -9 /home/vagrant/bin/nomad
    ignore_errors: yes

  - name: Run nomad server
    command: screen -dmS nomad /home/vagrant/bin/nomad agent -config ./nomad_client.hcl
    args:
      chdir: /home/vagrant/nomad_client/
